name: Deploy
run -name: ${{ github.actor }} deployed
on:
  push:
   branches:
     - main
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: make build
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
